import pymongo.database
from typing import Any, Dict, List, Tuple, Union

class Collection:
    def __init__(self, database: pymongo.database.Database, name: str) -> None: ...
    def create_index(self, keys: Union[str, List[Tuple[str, int]]]) -> None: ...
    def save(self, doc: Dict[str, Any]) -> None: ...
