import pymongo.mongo_client
import pymongo.collection

class Database:
    def __init__(self, client: pymongo.mongo_client.MongoClient) -> None: ...
    def create_collection(self, name: str, capped: bool=False, size: int=0) -> None: ...
    def __getitem__(self, name: str) -> pymongo.collection.Collection: ...

